# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amplifer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1113, 900)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(60, 30, 1011, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(270, 30, 531, 51))
        self.label_10.setStyleSheet("font: 24pt \"隶书\";\n"
"color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.994318 rgba(234, 164, 145, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"font: 30pt \"Arial Unicode MS\";")
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(200, 10, 101, 101))
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setMaximumSize(QtCore.QSize(271, 261))
        self.label_3.setStyleSheet("image: url(:/pic/imag/QQ.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/pic/E:/QT/Amplifer/imag/QQ.png"))
        self.label_3.setObjectName("label_3")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(60, 160, 1011, 641))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(30, 450, 291, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_update_program = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_update_program.setGeometry(QtCore.QRect(80, 40, 111, 41))
        self.pushButton_update_program.setObjectName("pushButton_update_program")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 40, 291, 171))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 30, 161, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout.addWidget(self.lineEdit_ip)
        self.lineEdit_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.verticalLayout.addWidget(self.lineEdit_port)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 29, 129, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout_2.addWidget(self.label_ip)
        self.label_port = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_port.setObjectName("label_port")
        self.verticalLayout_2.addWidget(self.label_port)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 54, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/pic/E:/QT/Amplifer/imag/icon_enoff.ICO"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(40, 110, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/pic/imag/icon_enoff.ICO"))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(120, 110, 160, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_ip_connect = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_ip_connect.setObjectName("pushButton_ip_connect")
        self.horizontalLayout_9.addWidget(self.pushButton_ip_connect)
        self.pushButton_ip_disconnect = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_ip_disconnect.setObjectName("pushButton_ip_disconnect")
        self.horizontalLayout_9.addWidget(self.pushButton_ip_disconnect)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(30, 230, 291, 201))
        self.groupBox_8.setObjectName("groupBox_8")
        self.frame = QtWidgets.QFrame(self.groupBox_8)
        self.frame.setGeometry(QtCore.QRect(20, 20, 261, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.frame)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 19, 231, 121))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_7)
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.horizontalLayout_8.addWidget(self.textBrowser_recv)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setGeometry(QtCore.QRect(350, 230, 381, 201))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(20, 70, 51, 80))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_7.addWidget(self.label_11)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_7.addWidget(self.label_12)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(70, 70, 101, 80))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lineEdit_threshold = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.lineEdit_threshold.setObjectName("lineEdit_threshold")
        self.verticalLayout_10.addWidget(self.lineEdit_threshold)
        self.lineEdit_stapA = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.lineEdit_stapA.setObjectName("lineEdit_stapA")
        self.verticalLayout_10.addWidget(self.lineEdit_stapA)
        self.lineEdit_stapB = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.lineEdit_stapB.setObjectName("lineEdit_stapB")
        self.verticalLayout_10.addWidget(self.lineEdit_stapB)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(20, 20, 341, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(190, 70, 51, 80))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_12.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget_12)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_12.addWidget(self.label_15)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_9)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(240, 70, 121, 81))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_Frequency = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.lineEdit_Frequency.setObjectName("lineEdit_Frequency")
        self.verticalLayout_13.addWidget(self.lineEdit_Frequency)
        self.lineEdit_Amplitude = QtWidgets.QLineEdit(self.verticalLayoutWidget_13)
        self.lineEdit_Amplitude.setObjectName("lineEdit_Amplitude")
        self.verticalLayout_13.addWidget(self.lineEdit_Amplitude)
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.groupBox_9)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(20, 150, 341, 41))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.pushButton_stap_read = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_stap_read.setObjectName("pushButton_stap_read")
        self.horizontalLayout_12.addWidget(self.pushButton_stap_read)
        self.pushButton_stap_set = QtWidgets.QPushButton(self.horizontalLayoutWidget_11)
        self.pushButton_stap_set.setObjectName("pushButton_stap_set")
        self.horizontalLayout_12.addWidget(self.pushButton_stap_set)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 40, 381, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 341, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_current = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_current.setObjectName("radioButton_current")
        self.horizontalLayout.addWidget(self.radioButton_current)
        self.radioButton_voltage = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_voltage.setObjectName("radioButton_voltage")
        self.horizontalLayout.addWidget(self.radioButton_voltage)
        self.radioButton_digital = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_digital.setObjectName("radioButton_digital")
        self.horizontalLayout.addWidget(self.radioButton_digital)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(110, 70, 160, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_input_set = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_input_set.setObjectName("lineEdit_input_set")
        self.horizontalLayout_2.addWidget(self.lineEdit_input_set)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(20, 110, 341, 41))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButton_input_parameter_read = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_input_parameter_read.setObjectName("pushButton_input_parameter_read")
        self.horizontalLayout_10.addWidget(self.pushButton_input_parameter_read)
        self.pushButton_input_parameter_set = QtWidgets.QPushButton(self.horizontalLayoutWidget_9)
        self.pushButton_input_parameter_set.setObjectName("pushButton_input_parameter_set")
        self.horizontalLayout_10.addWidget(self.pushButton_input_parameter_set)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(750, 40, 241, 551))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(9, 19, 221, 521))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_10)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 58, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(90, 30, 111, 62))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_spool_current_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_spool_current_p.setObjectName("lineEdit_spool_current_p")
        self.verticalLayout_6.addWidget(self.lineEdit_spool_current_p)
        self.lineEdit_spool_current_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_spool_current_i.setObjectName("lineEdit_spool_current_i")
        self.verticalLayout_6.addWidget(self.lineEdit_spool_current_i)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_5)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(20, 100, 181, 41))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_spool_current_read = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_spool_current_read.setObjectName("pushButton_spool_current_read")
        self.horizontalLayout_6.addWidget(self.pushButton_spool_current_read)
        self.pushButton_spool_current_set = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_spool_current_set.setObjectName("pushButton_spool_current_set")
        self.horizontalLayout_6.addWidget(self.pushButton_spool_current_set)
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 160, 221, 181))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 61, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_spool_displacement_p = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_p.setObjectName("label_spool_displacement_p")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_p)
        self.label_spool_displacement_i = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_i.setObjectName("label_spool_displacement_i")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_i)
        self.label_spool_displacement_d = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_d.setObjectName("label_spool_displacement_d")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_d)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(90, 30, 111, 81))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_spool_displacement_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_p.setObjectName("lineEdit_spool_displacement_p")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_p)
        self.lineEdit_spool_displacement_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_i.setObjectName("lineEdit_spool_displacement_i")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_i)
        self.lineEdit_spool_displacement_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_d.setObjectName("lineEdit_spool_displacement_d")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_d)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 120, 181, 41))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_spool_displacement_read = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_spool_displacement_read.setObjectName("pushButton_spool_displacement_read")
        self.horizontalLayout_5.addWidget(self.pushButton_spool_displacement_read)
        self.pushButton_spool_displacement_set = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.pushButton_spool_displacement_set.setObjectName("pushButton_spool_displacement_set")
        self.horizontalLayout_5.addWidget(self.pushButton_spool_displacement_set)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 340, 221, 171))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 58, 81))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_piston_displacement_p = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_p.setObjectName("label_piston_displacement_p")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_p)
        self.label_piston_displacement_i = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_i.setObjectName("label_piston_displacement_i")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_i)
        self.label_piston_displacement_d = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_d.setObjectName("label_piston_displacement_d")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_d)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(90, 30, 111, 81))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_piston_displacement_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_p.setObjectName("lineEdit_piston_displacement_p")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_p)
        self.lineEdit_piston_displacement_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_i.setObjectName("lineEdit_piston_displacement_i")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_i)
        self.lineEdit_piston_displacement_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_d.setObjectName("lineEdit_piston_displacement_d")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_d)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_7)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 120, 181, 41))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_piston_displacement_read = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_piston_displacement_read.setObjectName("pushButton_piston_displacement_read")
        self.horizontalLayout_4.addWidget(self.pushButton_piston_displacement_read)
        self.pushButton_piston_displacement_set = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pushButton_piston_displacement_set.setObjectName("pushButton_piston_displacement_set")
        self.horizontalLayout_4.addWidget(self.pushButton_piston_displacement_set)
        self.verticalLayout_9.addWidget(self.groupBox_5)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tabWidget.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">伺服比例阀控制系统</span></p></body></html>"))
        self.groupBox_4.setTitle(_translate("MainWindow", "更新程序"))
        self.pushButton_update_program.setText(_translate("MainWindow", "更新程序"))
        self.groupBox.setTitle(_translate("MainWindow", "服务器设置"))
        self.label_ip.setText(_translate("MainWindow", "   IP地址"))
        self.label_port.setText(_translate("MainWindow", "   端口号"))
        self.pushButton_ip_connect.setText(_translate("MainWindow", "连接"))
        self.pushButton_ip_disconnect.setText(_translate("MainWindow", "断开"))
        self.groupBox_8.setTitle(_translate("MainWindow", "控制指令显示"))
        self.groupBox_9.setTitle(_translate("MainWindow", "颤振和电流阶跃设置"))
        self.label_11.setText(_translate("MainWindow", "阈值"))
        self.label_9.setText(_translate("MainWindow", "阶跃A"))
        self.label_12.setText(_translate("MainWindow", "阶跃B"))
        self.label_7.setText(_translate("MainWindow", "电流阶跃："))
        self.label_13.setText(_translate("MainWindow", "颤振信号："))
        self.label_14.setText(_translate("MainWindow", "频率"))
        self.label_15.setText(_translate("MainWindow", "幅值"))
        self.pushButton_stap_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_stap_set.setText(_translate("MainWindow", "设置完成"))
        self.groupBox_3.setTitle(_translate("MainWindow", "输入类型设置"))
        self.radioButton_current.setText(_translate("MainWindow", "电流"))
        self.radioButton_voltage.setText(_translate("MainWindow", "电压"))
        self.radioButton_digital.setText(_translate("MainWindow", "数字设定（-1000~1000）"))
        self.label.setText(_translate("MainWindow", "设定值"))
        self.pushButton_input_parameter_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_input_parameter_set.setText(_translate("MainWindow", "设置完成"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PID控制"))
        self.groupBox_5.setTitle(_translate("MainWindow", "阀芯电流闭环PI参数设置"))
        self.label_2.setText(_translate("MainWindow", "比例(P)"))
        self.label_4.setText(_translate("MainWindow", "积分(I)"))
        self.pushButton_spool_current_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_spool_current_set.setText(_translate("MainWindow", "设置完成"))
        self.groupBox_6.setTitle(_translate("MainWindow", "阀芯位移闭环PID参数设置"))
        self.label_spool_displacement_p.setText(_translate("MainWindow", "比例(P)"))
        self.label_spool_displacement_i.setText(_translate("MainWindow", "积分(I)"))
        self.label_spool_displacement_d.setText(_translate("MainWindow", "微分(D)"))
        self.pushButton_spool_displacement_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_spool_displacement_set.setText(_translate("MainWindow", "设置完成"))
        self.groupBox_7.setTitle(_translate("MainWindow", "活塞位置闭环PID参数设置"))
        self.label_piston_displacement_p.setText(_translate("MainWindow", "比例(P)"))
        self.label_piston_displacement_i.setText(_translate("MainWindow", "积分(I)"))
        self.label_piston_displacement_d.setText(_translate("MainWindow", "微分(D)"))
        self.pushButton_piston_displacement_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_piston_displacement_set.setText(_translate("MainWindow", "设置完成"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "参数设置"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "曲线显示"))
        self.lineEdit_ip.setInputMask("000.000.000.000;_")
        self.lineEdit_ip.setInputMask("00.00.000.000;_")
        self.lineEdit_ip.setPlaceholderText("10.13.106.216")
        self.lineEdit_ip.setText("10.13.106.216")
        self.lineEdit_port.setText("8080")
        self.lineEdit_port.setPlaceholderText("8080")
        self.lineEdit_input_set.setText('0')
        self.lineEdit_threshold.setText('0')
        self.lineEdit_stapA.setText('0')
        self.lineEdit_stapB.setText('0')
        self.lineEdit_Frequency.setText('0')
        self.lineEdit_Amplitude.setText('0')
        self.lineEdit_spool_current_p.setText('0')
        self.lineEdit_spool_current_i.setText('0')
        self.lineEdit_spool_displacement_p.setText('0')
        self.lineEdit_spool_displacement_i.setText('0')
        self.lineEdit_spool_displacement_d.setText('0')
        self.lineEdit_piston_displacement_p.setText('0')
        self.lineEdit_piston_displacement_i.setText('0')
        self.lineEdit_piston_displacement_d.setText('0')
        MainWindow.setFixedSize(1200, 850)


import apprcc_rc
