# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Amplifer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1136, 770)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(60, 30, 931, 121))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(270, 30, 391, 51))
        self.label_10.setStyleSheet("font: 24pt \"隶书\";\n"
"color: qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0.994318 rgba(234, 164, 145, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"font: 30pt \"Arial Unicode MS\";")
        self.label_10.setObjectName("label_10")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(110, 10, 101, 101))
        self.label_3.setMinimumSize(QtCore.QSize(50, 50))
        self.label_3.setMaximumSize(QtCore.QSize(271, 261))
        self.label_3.setStyleSheet("image: url(:/pic/imag/QQ.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/pic/E:/QT/Amplifer/imag/QQ.png"))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(70, 170, 281, 161))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 30, 121, 71))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.verticalLayout.addWidget(self.lineEdit_ip)
        self.lineEdit_port = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.verticalLayout.addWidget(self.lineEdit_port)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 29, 74, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_ip = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_ip.setObjectName("label_ip")
        self.verticalLayout_2.addWidget(self.label_ip)
        self.label_port = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_port.setObjectName("label_port")
        self.verticalLayout_2.addWidget(self.label_port)
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(100, 110, 160, 31))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.pushButton_ip_connect = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_ip_connect.setObjectName("pushButton_ip_connect")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_ip_connect)
        self.pushButton_ip_disconnect = QtWidgets.QPushButton(self.formLayoutWidget_2)
        self.pushButton_ip_disconnect.setObjectName("pushButton_ip_disconnect")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_ip_disconnect)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 54, 16))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/pic/E:/QT/Amplifer/imag/icon_enoff.ICO"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(30, 110, 31, 31))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/pic/imag/icon_enoff.ICO"))
        self.label_6.setObjectName("label_6")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(90, 610, 121, 81))
        self.groupBox_4.setObjectName("groupBox_4")
        self.pushButton_update_program = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_update_program.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.pushButton_update_program.setObjectName("pushButton_update_program")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(400, 170, 381, 161))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 339, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_current = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_current.setObjectName("radioButton_current")
        self.horizontalLayout.addWidget(self.radioButton_current)
        self.radioButton_voltage = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_voltage.setObjectName("radioButton_voltage")
        self.horizontalLayout.addWidget(self.radioButton_voltage)
        self.radioButton_digital = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_digital.setObjectName("radioButton_digital")
        self.horizontalLayout.addWidget(self.radioButton_digital)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 70, 160, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_input_set = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_input_set.setObjectName("lineEdit_input_set")
        self.horizontalLayout_2.addWidget(self.lineEdit_input_set)
        self.pushButton_input_parameter_read = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_input_parameter_read.setGeometry(QtCore.QRect(40, 120, 75, 23))
        self.pushButton_input_parameter_read.setObjectName("pushButton_input_parameter_read")
        self.pushButton_input_parameter_set = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_input_parameter_set.setGeometry(QtCore.QRect(200, 120, 75, 23))
        self.pushButton_input_parameter_set.setObjectName("pushButton_input_parameter_set")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(90, 380, 251, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textEdit_send = QtWidgets.QTextEdit(self.frame)
        self.textEdit_send.setGeometry(QtCore.QRect(10, 40, 81, 61))
        self.textEdit_send.setObjectName("textEdit_send")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser_recv.setGeometry(QtCore.QRect(110, 50, 131, 51))
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.pushButton_send = QtWidgets.QPushButton(self.frame)
        self.pushButton_send.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton_send.setObjectName("pushButton_send")
        self.pushButton_clear = QtWidgets.QPushButton(self.frame)
        self.pushButton_clear.setGeometry(QtCore.QRect(130, 20, 75, 23))
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(880, 200, 211, 511))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(10, 20, 191, 481))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.verticalLayoutWidget_9)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 58, 61))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(90, 30, 91, 62))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_spool_current_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_spool_current_p.setObjectName("lineEdit_spool_current_p")
        self.verticalLayout_6.addWidget(self.lineEdit_spool_current_p)
        self.lineEdit_spool_current_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        self.lineEdit_spool_current_i.setObjectName("lineEdit_spool_current_i")
        self.verticalLayout_6.addWidget(self.lineEdit_spool_current_i)
        self.pushButton_spool_current_read = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_spool_current_read.setGeometry(QtCore.QRect(20, 110, 75, 23))
        self.pushButton_spool_current_read.setObjectName("pushButton_spool_current_read")
        self.pushButton_spool_current_set = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_spool_current_set.setGeometry(QtCore.QRect(100, 110, 75, 23))
        self.pushButton_spool_current_set.setObjectName("pushButton_spool_current_set")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 150, 201, 171))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(20, 30, 58, 81))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_piston_displacement_p = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_p.setObjectName("label_piston_displacement_p")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_p)
        self.label_piston_displacement_i = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_i.setObjectName("label_piston_displacement_i")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_i)
        self.label_piston_displacement_d = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_piston_displacement_d.setObjectName("label_piston_displacement_d")
        self.verticalLayout_5.addWidget(self.label_piston_displacement_d)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(80, 30, 91, 95))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_piston_displacement_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_p.setObjectName("lineEdit_piston_displacement_p")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_p)
        self.lineEdit_piston_displacement_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_i.setObjectName("lineEdit_piston_displacement_i")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_i)
        self.lineEdit_piston_displacement_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        self.lineEdit_piston_displacement_d.setObjectName("lineEdit_piston_displacement_d")
        self.verticalLayout_11.addWidget(self.lineEdit_piston_displacement_d)
        self.pushButton_piston_displacement_set = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_piston_displacement_set.setGeometry(QtCore.QRect(100, 120, 75, 23))
        self.pushButton_piston_displacement_set.setObjectName("pushButton_piston_displacement_set")
        self.pushButton_piston_displacement_read = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_piston_displacement_read.setGeometry(QtCore.QRect(20, 120, 75, 23))
        self.pushButton_piston_displacement_read.setObjectName("pushButton_piston_displacement_read")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(0, 330, 191, 151))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(90, 30, 270, 337))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.lineEdit_spool_displacement_p = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_p.setObjectName("lineEdit_spool_displacement_p")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_p)
        self.lineEdit_spool_displacement_i = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_i.setObjectName("lineEdit_spool_displacement_i")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_i)
        self.lineEdit_spool_displacement_d = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        self.lineEdit_spool_displacement_d.setObjectName("lineEdit_spool_displacement_d")
        self.verticalLayout_8.addWidget(self.lineEdit_spool_displacement_d)
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 120, 160, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pushButton_spool_displacement_read = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_spool_displacement_read.setObjectName("pushButton_spool_displacement_read")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton_spool_displacement_read)
        self.pushButton_spool_displacement_set = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pushButton_spool_displacement_set.setObjectName("pushButton_spool_displacement_set")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_spool_displacement_set)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_6)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 61, 81))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_spool_displacement_p = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_p.setObjectName("label_spool_displacement_p")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_p)
        self.label_spool_displacement_i = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_i.setObjectName("label_spool_displacement_i")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_i)
        self.label_spool_displacement_d = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_spool_displacement_d.setObjectName("label_spool_displacement_d")
        self.verticalLayout_4.addWidget(self.label_spool_displacement_d)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#000000;\">伺服比例阀控制系统</span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "服务器设置"))
        self.label_ip.setText(_translate("MainWindow", "   IP地址"))
        self.label_port.setText(_translate("MainWindow", "   端口号"))
        self.pushButton_ip_connect.setText(_translate("MainWindow", "连接"))
        self.pushButton_ip_disconnect.setText(_translate("MainWindow", "断开"))
        self.groupBox_4.setTitle(_translate("MainWindow", "更新程序"))
        self.pushButton_update_program.setText(_translate("MainWindow", "更新程序"))
        self.groupBox_3.setTitle(_translate("MainWindow", "输入类型设置"))
        self.radioButton_current.setText(_translate("MainWindow", "电流"))
        self.radioButton_voltage.setText(_translate("MainWindow", "电压"))
        self.radioButton_digital.setText(_translate("MainWindow", "数字设定（-1000~1000）"))
        self.label.setText(_translate("MainWindow", "设定值"))
        self.pushButton_input_parameter_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_input_parameter_set.setText(_translate("MainWindow", "设置完成"))
        self.pushButton_send.setText(_translate("MainWindow", "发送"))
        self.pushButton_clear.setText(_translate("MainWindow", "清除"))
        self.groupBox_2.setTitle(_translate("MainWindow", "PID控制"))
        self.groupBox_5.setTitle(_translate("MainWindow", "阀芯电流闭环PI参数设置"))
        self.label_2.setText(_translate("MainWindow", "比例(P)"))
        self.label_4.setText(_translate("MainWindow", "积分(I)"))
        self.pushButton_spool_current_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_spool_current_set.setText(_translate("MainWindow", "设置完成"))
        self.groupBox_7.setTitle(_translate("MainWindow", "活塞位置闭环PID参数设置"))
        self.label_piston_displacement_p.setText(_translate("MainWindow", "比例(P)"))
        self.label_piston_displacement_i.setText(_translate("MainWindow", "积分(I)"))
        self.label_piston_displacement_d.setText(_translate("MainWindow", "微分(D)"))
        self.pushButton_piston_displacement_set.setText(_translate("MainWindow", "设置完成"))
        self.pushButton_piston_displacement_read.setText(_translate("MainWindow", "参数读取"))
        self.groupBox_6.setTitle(_translate("MainWindow", "阀芯位移闭环PID参数设置"))
        self.pushButton_spool_displacement_read.setText(_translate("MainWindow", "参数读取"))
        self.pushButton_spool_displacement_set.setText(_translate("MainWindow", "设置完成"))
        self.label_spool_displacement_p.setText(_translate("MainWindow", "比例(P)"))
        self.label_spool_displacement_i.setText(_translate("MainWindow", "积分(I)"))
        self.label_spool_displacement_d.setText(_translate("MainWindow", "微分(D)"))

        # self.lineEdit_ip.setInputMask("00.00.000.000;_")
        # self.lineEdit_ip.setPlaceholderText("10.13.106.216")
        self.lineEdit_ip.setText("10.13.106.216")
        self.lineEdit_port.setText("8080")
        self.lineEdit_port.setPlaceholderText("8080")

import apprcc_rc
